import { db } from '../db';
import { todosTable } from '../db/schema';
import { type CreateTodoInput, type Todo } from '../schema';

export const createTodo = async (input: CreateTodoInput): Promise<Todo> => {
  try {
    // Insert todo record
    const result = await db.insert(todosTable)
      .values({
        title: input.title,
        description: input.description || null // Handle optional nullable field
        // completed defaults to false (defined in schema)
        // created_at will be auto-generated by database
      })
      .returning()
      .execute();

    // Return the created todo
    const todo = result[0];
    return {
      ...todo,
      // No numeric conversions needed - all fields are already correct types
    };
  } catch (error) {
    console.error('Todo creation failed:', error);
    throw error;
  }
};